# Generated by Django 5.2.7 on 2025-10-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0002_brightdatasnapshot_error_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
