# Generated by Django 5.2.7 on 2025-10-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0005_brightdatasnapshot_progress_check_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='_status',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='last_result_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='last_status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
