# Generated by Django 5.2.7 on 2025-10-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(db_index=True, max_length=120)),
                ('url', models.URLField(db_index=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('comments', models.JSONField(blank=True, null=True)),
                ('related_posts', models.JSONField(blank=True, null=True)),
                ('community_name', models.TextField(blank=True, null=True)),
                ('num_upvotes', models.IntegerField(blank=True, null=True)),
                ('num_comments', models.IntegerField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
